-- Insert light data
INSERT INTO lights (name, manufacturer) VALUES
('LE330h', 'INON'),
('LE350', 'INON'),
('LE600h-S', 'INON'),
('LE600h-W', 'INON'),
('LE700-S', 'INON'),
('LE700-W', 'INON'),
('LF650h-N', 'INON'),
('LF800-N', 'INON'),
('LF1000-S', 'INON'),
('LF1100h-EWf', 'INON'),
('LF1300-EWf', 'INON'),
('LF1400-S', 'INON'),
('LF2400h-EW', 'INON'),
('LF2700-W', 'INON'),
('LF3100-EW', 'INON'),
('S5', 'RGBlue'),
('SYSTEM01:re Single Light SUPER-NATURAL COLOR', 'RGBlue'),
('SYSTEM01:re Single Light Premium Color', 'RGBlue'),
('SYSTEM02:re Single Light SUPER-NATURAL COLOR', 'RGBlue'),
('SYSTEM02:re Single Light Premium Color', 'RGBlue'),
('SYSTEM01:re Twin Light SUPER-NATURAL COLOR', 'RGBlue'),
('SYSTEM01:re Twin Light Module PREMIUM COLOR', 'RGBlue'),
('SYSTEM02:re Twin Light SUPER-NATURAL COLOR', 'RGBlue'),
('SYSTEM02:re Twin Light Module PREMIUM COLOR', 'RGBlue'),
('SYSTEM01:re Spot Beam', 'RGBlue'),
('SYSTEM02:re Spot Beam', 'RGBlue'),
('LX-1200SW FS', 'Fisheye'),
('LX-2400SW FS', 'Fisheye'),
('FIX NEO 1500 DX SW II', 'Fisheye'),
('LX-4000SW FS', 'Fisheye'),
('FIX NEO Premium 4030 EF II', 'Fisheye'),
('FIX NEO Premium 1500DX SWRII FS', 'Fisheye'),
('FIX NEO Premium 3000DX SWRII FS', 'Fisheye'),
('FIX リングライト 1500', 'Fisheye'),
('FIXリングディフューザーTG', 'Fisheye'),
('FIX リングライト 1000', 'Fisheye'),
('FIX AQUAVOLT 7000α', 'Fisheye'),
('FIX AQUAVOLT 5000Mini', 'Fisheye'),
('WF SmartFocus 1200FR 2025II', 'Fisheye'),
('Weefine WF Smart Focus 2600', 'Fisheye'),
('Weefine WF Smart Focus 1000', 'Fisheye'),
('Weefine WF Ring Light 3018', 'Fisheye'),
('Weefine WF Solar Flare 12000', 'Fisheye'),
('Weefine WF Solar Flare 13000PRO', 'Fisheye'),
('Weefine WF Solar Flare 7000S', 'Fisheye');

-- Insert strobe data
INSERT INTO strobes (name, manufacturer) VALUES
('YS-D130R', 'sea&sea'),
('YS-D3 DUO', 'sea&sea'),
('YS-01 SOLIS', 'sea&sea'),
('YS-03 SOLIS', 'sea&sea'),
('YS-D3 MKII LIGHTNING', 'sea&sea'),
('S-220', 'INON'),
('D-200', 'INON'),
('Z-330', 'INON'),
('S-2000', 'INON'),
('AOI-UCS-Q1-RC-BLK', 'AOI'),
('AOI-UCS-Q1-RC-WHT', 'AOI'),
('Apollo S', 'marelux'),
('Apollo44', 'marelux');

-- Insert accessory data
INSERT INTO accessories (name, company) VALUES
('WF ワイドコンバージョンレンズUWL-24M52MG', 'Fisheye'),
('ワイドコンバージョンレンズUWL-95S XD', 'Fisheye'),
('ワイドコンバージョンレンズUWL-95S M52', 'Fisheye'),
('UCL-05L', 'AOI'),
('UCL-06L', 'AOI'),
('UCL-09PRO', 'AOI'),
('UCL-90PRO', 'AOI'),
('UCL-900PRO', 'AOI'),
('UWL-09', 'AOI'),
('UWL-09 PRO', 'AOI');